name: Размещение на GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Сборка HTML
        run: docker run --rm -v $(pwd)/src:/docs -v $(pwd)/htdocs:/opt/build mekras/sphinx-doc:latest make html

      - uses: actions/upload-pages-artifact@v3
        with:
          path: htdocs/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
